import { generateFlags } from "../generate_schema/mod.ts";

export const treeLintFlags = generateFlags([
  `useDynamicRoots?: boolean`,
  `removeUnrecognizedEdges?: boolean`,
  `flipRelationFiles?: string[]`,
  `keepFiles?: string[]`,
  `indexName?: string | string[]`,
  `excludeBasenames?: string | string[]`,
  `excludeDirnames?: string | string[]`,
  `excludeParentDirnames?: string | string[]`,
  `excludeRootDirnames?: string | string[]`,
  `excludeNode?: string | string[]| undefined`,
  `promoteBasenames?: string | string[]`,
  `promoteDirnames?: string | string[]`,
  `promoteParentDirnames?: string | string[]`,
  `promoteRootDirnames?: string | string[]`,
  `promoteNode?: string | string[]`,
  `deduplicateStyle?: "shortest" | "longest"`,
  `addUnusedGraphNodes?: boolean`,
  `withTypes?: boolean`,
  `recursive?: boolean`,
  `extensions?: string[]`,
  `json?: boolean`,
  `actual?: boolean`,
  `expected?: boolean`,
  "noMessage?: boolean",
  "noAssert?: boolean",
  "hideAssert?: boolean",
]);
